provider azurerm {
  features {}
}

locals {
  images = [
    "image_file",
    "birkenhead_county_court.jpg",
    "kettering_magistrates_court.jpg",
    "alton_magistrates_court.jpg",
    "andover_magistrates_court.jpg",
    "aldridge_magistrates_court.jpg",
    "bury_county_court.jpg",
    "surrey_fixed_penalty_office.jpg",
    "stockport_magistrates_court_and_family_court.jpg",
    "bolton_county_court.jpg",
    "cardiff_probate_registry_of_wales.jpg",
    "bolton_magistrates_court.jpg",
    "south_sefton_magistrates_court.jpg",
    "canterbury_combined_court_centre.jpg",
    "upper_tribunal_lands_chamber.jpg",
    "hertford_county_court.jpg",
    "banbury_magistrates_court.jpg",
    "northampton_social_security_and_child_support_tribunal.jpg",
    "residential_property_midlands_region_first_tier_tribunal_property_chamber.jpg",
    "york_magistrates_court.jpg",
    "manchester_immigration_and_asylum_chamber_first_tier_tribunal.jpg",
    "bury_st_edmunds_crown_court.jpg",
    "aylesbury_crown_court.jpg",
    "yarl_s_wood_immigration_and_asylum_hearing_centre.jpg",
    "burton_upon_trent_magistrates_court.jpg",
    "bury_and_rochdale_magistrates_court.jpg",
    "devon_cornwall_fixed_penalty_office.gif",
    "inner_london_family_proceedings_court.jpg",
    "denbigh_magistrates_court.jpg",
    "chester_probate_sub_registry.jpg",
    "grantham_magistrates_court.jpg",
    "bournemouth_crown_court.jpg",
    "northampton_county_court_bulk_centre.jpg",
    "bridlington_magistrates_court.jpg",
    "newcastle_social_security_and_child_support_tribunal.jpeg",
    "chelmsford_crown_court.jpg",
    "stirling_social_security_and_child_support_tribunal.jpg",
    "east_london_family_court.jpg",
    "chester_crown_court.jpg",
    "west_london_family_court.jpg",
    "bodmin_probate_sub_registry.jpg",
    "burnley_magistrates_court.jpg",
    "central_london_county_court_bankruptcy.jpg",
    "gloucester_probate_sub_registry.jpg",
    "cambridge_magistrates_court.jpg",
    "chichester_magistrates_court.jpg",
    "hove_trial_centre.jpg",
    "harlow_magistrates_court.jpg",
    "lancaster_probate_sub_registry.jpg",
    "truro_crown_court.jpg",
    "lambeth_county_court.jpg",
    "cannock_magistrates_court.jpg",
    "dover_magistrates_court.jpg",
    "knutsford_crown_court.jpg",
    "southport_magistrates_court.jpg",
    "hertford_magistrates_court.jpg",
    "isles_of_scilly_magistrates_court.jpg",
    "city_of_london_magistrates_court.jpg",
    "hereford_crown_court.jpg",
    "eastbourne_magistrates_court.jpg",
    "hastings_magistrates_court.jpg",
    "isleworth_crown_court.jpg",
    "guildford_crown_court.jpg",
    "kingston_upon_thames_crown_court.jpg",
    "hamilton_social_security_and_child_support_tribunal.jpg",
    "leicester-magistrates-court.jpg",
    "hereford_magistrates_court.jpg",
    "kingston_upon_hull_magistrates_court.jpg",
    "gloucester_crown_court.jpg",
    "exeter_magistrates_court_north_and_east_devon.jpg",
    "great_yarmouth_magistrates_court.jpg",
    "derby_magistrates_court.jpg",
    "harrow_crown_court.jpg",
    "cambridge_crown_court.jpg",
    "central_criminal_court.jpg",
    "chester-magistrates-court.jpg",
    "luton_crown_court.jpg",
    "redditch_magistrates_court.jpg",
    "maidstone_probate_sub_registry.jpg",
    "reedley_magistrates_court.jpg",
    "lincoln_probate_sub_registry.jpg",
    "redhill_magistrates_court.jpg",
    "guildford_magistrates_court.jpg",
    "king_s_lynn_magistrates_court.jpg",
    "west_berkshire_magistrates_court_newbury.jpg",
    "solihull_magistrates_court.jpg",
    "shrewsbury_magistrates_court.jpg",
    "manchester_and_salford_magistrates_court.jpg",
    "medway_magistrates_court.jpg",
    "leicester_crown_court.jpg",
    "lincoln_magistrates_court.jpg",
    "nottingham-crown-court.jpg",
    "manchester_crown_court_crown_square.jpg",
    "ipswich_crown_court.jpg",
    "llandudno-magistrates-court.jpg",
    "king_s_lynn_crown_court.jpg",
    "east_berkshire_magistrates_court_maidenhead.jpg",
    "reading_magistrates_court.jpg",
    "ipswich_magistrates_court.jpg",
    "north_shields_county_court.jpg",
    "south_worcestershire_magistrates_court.jpg",
    "romford_magistrates_court_formerly_havering_magistrates_court.jpg",
    "lincoln-county-court-and-family-court.jpg",
    "blackburn_magistrates_court.jpg",
    "nottingham_probate_sub_registry.jpg",
    "wirral_magistrates_court.jpg",
    "torquay_magistrates_court.jpg",
    "spalding_magistrates_court.jpg",
    "tower_bridge_magistrates_court.jpg",
    "skegness_magistrates_court.jpg",
    "technology_construction_court.jpg",
    "claim_production_centre_cpc.jpg",
    "staines_magistrates_court.jpg",
    "sheffield_probate_sub_registry.jpg",
    "northampton_magistrates_court.jpg",
    "poole_magistrates_court.png",
    "oxford_district_probate_registry.jpg",
    "lancaster_county_court_and_family_court.jpg",
    "plymouth_magistrates_court.jpg",
    "peterborough_magistrates_court.jpg",
    "worksop_magistrates_court.jpg",
    "colchester_magistrates_court.jpg",
    "southend_magistrates_court.jpg",
    "south_cheshire_magistrates_court.jpg",
    "walsall_magistrates_court.jpg",
    "sevenoaks_magistrates_court.jpg",
    "telford_magistrates_court.jpg",
    "skipton_magistrates_court.jpg",
    "shrewsbury-crown-court.jpg",
    "walsall_county_court.jpg",
    "vale_of_glamorgan_magistrates_court.jpg",
    "staffs_central_finance_and_enforcement_unit.jpg",
    "st_albans_crown_court.jpg",
    "southend_crown_court.jpg",
    "woolwich_crown_court.jpg",
    "sandwell_magistrates_court.jpg",
    "hammersmith_magistrates_court.jpg",
    "west_somerset_magistrates_court.jpg",
    "hampshire_the_isle_of_wight_fixed_penalty_office.gif",
    "surrey_fines_and_enforcement_unit.jpg",
    "sussex_fines_enforcement_unit.gif",
    "family_division.jpg",
    "dolgellau_crown_court.jpg",
    "banbury_fixed_penalty_office.gif",
    "stourbridge_county_court.jpg",
    "east_london_family_proceedings_court.jpg",
    "national_taxing_team_manchester_office.jpg",
    "national_taxing_team_birmingham_office.jpg",
    "wolverhampton_magistrates_court.jpg",
    "wigan_and_leigh_magistrates_court.jpg",
    "west_hampshire_magistrates_court.jpg",
    "centralised_attachment_of_earnings_payments_caps.jpg",
    "manchester_district_probate_registry.gif",
    "stafford_magistrates_court.jpg",
    "north_yorkshire_enforcement_office.jpg",
    "huntingdon_law_courts.jpg",
    "court_of_appeal_civil_division.jpg",
    "london_mercantile_court.jpg",
    "queen_s_bench_division.jpg",
    "wood_green_crown_court.jpg",
    "stoke_on_trent_probate_sub_registry.jpg",
    "bolton-crown-court.jpg",
    "london_centralised_legal_aid_office.jpg",
    "haverfordwest_magistrates_court.jpg",
    "senior_courts_costs_office.jpg",
    "south_east_region_reciprocal_enforcement_unit.jpg",
    "st_albans_county_court.jpg",
    "gloucester_magistrates_court.jpg",
    "stroud_magistrates_court.jpg",
    "avon_somerset_fixed_penalty_office.jpg",
    "dolgellau_magistrates_court.jpg",
    "oldham_county_court.jpg",
    "worcester_combined_court.jpg",
    "chancery_division.jpg",
    "liverpool_district_probate_registry.jpg",
    "brighton_district_probate_registry.jpg",
    "blackburn_county_court.jpg",
    "loughborough_magistrates_court.jpg",
    "newport_south_wales_crown_court.jpg",
    "devon_and_cornwall_central_finance_unit.jpg",
    "luton_and_south_bedfordshire_magistrates_court.jpg",
    "pontypridd_county_court.jpg",
    "sunderland_county_court.jpg",
    "worcester_magistrates_court.jpg",
    "warwick_combined_court.jpg",
    "hatfield_magistrates_court.jpg",
    "patents_court.jpg",
    "liverpool_youth_court.jpg",
    "york_county_court.jpg",
    "south_shields_county_court.jpg",
    "norwich_probate_sub_registry.jpg",
    "bicester_magistrates_court.jpg",
    "north_avon_magistrates_court.jpg",
    "richmond_upon_thames_magistrates_court.jpg",
    "hinckley_magistrates_court.jpg",
    "nuneaton_county_court.jpg",
    "bodmin_magistrates_court.jpg",
    "wales_employment_tribunal.jpg",
    "london_probate_department.jpg",
    "north_liverpool_community_justice_centre.jpg",
    "oxford_and_southern_oxfordshire_magistrates_court.jpg",
    "horsham_magistrates_court.jpg",
    "middlesbrough_probate_sub_registry.jpg",
    "leeds_combined_court_centre.jpg",
    "basildon_combined_court.jpg",
    "teesside_combined_court_centre.jpg",
    "rolls_building.jpg",
    "welshpool_magistrates_court.jpg",
    "traffic_enforcement_centre_tec.jpg",
    "newcastle-upon-tyne-combined-court-centre.jpg",
    "wrexham_magistrates_and_county_courts.jpg",
    "liverpool_crown_court.jpg",
    "york_crown_court.jpg",
    "neath_and_port_talbot_county_court.jpg",
    "canterbury_magistrates_court.jpg",
    "margate_magistrates_court.jpg",
    "chesterfield_magistrates_court.jpg",
    "wigan_county_court.jpg",
    "glasgow_social_security_and_child_support_tribunal.jpg",
    "carlisle_combined_court_centre.jpg",
    "carlisle_probate_sub_registry.jpg",
    "waltham_forest_magistrates_court.jpg",
    "corby_magistrates_court.jpg",
    "newton_abbot_magistrates_court.jpg",
    "crawley_magistrates_court.jpg",
    "wales_enforcement_and_accounts_office.jpg",
    "bedford_and_mid_beds_magistrates_court.jpg",
    "newport_magistrates_court.jpg",
    "brighton_magistrates_court.jpg",
    "preston_magistrates_court.jpg",
    "brighton_family_court.jpg",
    "st_albans_magistrates_court.jpg",
    "folkestone_magistrates_court.jpg",
    "stevenage_magistrates_court.jpg",
    "luton_county_court.jpg",
    "warrington_magistrates_court.jpeg",
    "swindon_magistrates_court.jpg",
    "wolverhampton_combined_court_centre.jpg",
    "haverfordwest_county_court.jpg",
    "kendal_county_court.jpg",
    "doncaster_social_security_and_child_support_tribunal.jpg",
    "halifax_county_court.jpg",
    "teesside_magistrates_court.jpg",
    "barnsley_social_security_and_child_support_tribunal.jpg",
    "caernarfon_county_court_and_family_court.jpg",
    "leeds_district_magistrates_court.jpg",
    "doncaster_crown_court.jpg",
    "staines_county_court.jpg",
    "nottingham_employment_tribunal.jpg",
    "sheffield-family-hearing-centre.jpg",
    "kingston_upon_hull_combined_court_centre.jpg",
    "edinburgh_social_security_and_child_support_tribunal.jpg",
    "wakefield_civil_justice_centre.jpg",
    "grimsby_magistrates_court.jpg",
    "doncaster_magistrates_court.jpg",
    "llanelli_county_court.jpg",
    "dartford_county_court.jpg",
    "watford-county-court-and-family-court.jpg",
    "wellingborough_magistrates_court.jpg",
    "consett_magistrates_court.jpg",
    "durham_magistrates_court.jpg",
    "maintenance_enforcement_business_centre_wales.jpg",
    "high_peak_magistrates_court.jpg",
    "buxton_magistrates_court.jpg",
    "buxton_county_court.jpg",
    "west_london_county_court.jpg",
    "newcastle_upon_tyne_magistrates_court.jpg",
    "chippenham_and_trowbridge_law_courts.jpg",
    "mid_and_south_east_northumberland_magistrates_court.jpg",
    "bournemouth_and_poole_county_court.jpg",
    "milton_keynes_county_court.jpg",
    "horsham_county_court.jpg",
    "skipton_county_court.jpg",
    "newton_aycliffe_magistrates_court.jpg",
    "north_tyneside_magistrates_court.jpg",
    "leamington_spa_magistrates_court.jpg",
    "darlington_magistrates_court.jpg",
    "westminster_magistrates_court.jpg",
    "nottingham-magistrates-court.jpg",
    "south_tyneside_magistrates_court.jpg",
    "brentford_county_court.jpg",
    "guildford_county_court.jpg",
    "fareham_magistrates_court.jpg",
    "chesterfield_magistrates_court_county_court_and_family_court.jpg",
    "doncaster_regional_divorce_centre.bmp",
    "kettering_county_court.jpg",
    "durham_regional_divorce_centre.bmp",
    "midlands_west_employment_tribunal.jpg",
    "tunbridge_wells_county_court.jpg",
    "watford_magistrates_court.jpg",
    "snaresbrook_crown_court.jpg",
    "peterborough_combined_court_centre.jpg",
    "slough_county_court.jpg",
    "sheffield_combined_court_centre.jpg",
    "isle_of_wight_combined_court.jpg",
    "dundee_tribunal_hearing_centre.jpg",
    "scarborough_justice_centre.jpg",
    "great_grimsby_combined_court_centre.jpg",
    "hull_and_holderness_magistrates_court.jpg",
    "worthing_county_court.jpg",
    "bromley_magistrates_court.jpg",
    "barnstaple_crown_court.jpg",
    "bournemouth_magistrates_court.jpg",
    "aylesbury_county_court.jpg",
    "bodmin_county_court.jpg",
    "berwick_upon_tweed_magistrates_court.jpg",
    "leicester_probate_sub_registry.jpg",
    "beverley_magistrates_court.jpg",
    "durham_county_court.jpg",
    "salisbury_law_courts.bmp",
    "cheltenham_magistrates_court.jpg",
    "principal_registry_of_the_family_division.jpg",
    "bristol_crown_court.jpg",
    "swindon_combined_court.jpg",
    "bradford_and_keighley_magistrates_court.jpg",
    "exeter_combined_court_centre.jpg",
    "truro_county_court.jpg",
    "plymouth_combined_court.jpg",
    "carmarthen_probate_sub_registry.jpg",
    "banbury_county_court.jpg",
    "northallerton_magistrates_court.jpg",
    "oxford_combined_court_centre.jpg",
    "aylesbury_magistrates_court.jpg",
    "chester_le_street_magistrates_court.jpg",
    "barnet_civil_and_family_courts_centre.jpg",
    "barnstaple_magistrates_county_and_family_court.png",
    "barrow_in_furness_county_court.jpg",
    "basingstoke_county_court.jpg",
    "basingstoke_magistrates_court.jpg",
    "bedford_employment_social_security_and_child_support_tribunal.jpg",
    "maintenance_enforcement_centre_london.",
    "morpeth_and_berwick_county_court.jpg",
    "maidstone_magistrates_court.jpg",
    "lancaster_crown_court.jpg",
    "newport_south_wales_regional_divorce_centre.jpg",
    "stratford_housing_centre.jpg",
    "east_berkshire_magistrates_court_slough.jpg",
    "gateshead_county_court.jpg",
    "winchester_probate_registry.jpg",
    "west_cumbria_court_house.jpg",
    "bristol_district_probate_registry.jpg",
    "preston_combined_court_centre.jpeg",
    "kirklees_magistrates_court_formerly_huddersfield_magistrates_court.jpg",
    "norwich_social_security_and_child_support_tribunal.jpg",
    "gangmaster_licensing_appeals_england_wales_and_scotland.jpeg",
    "huddersfield_county_court.jpg",
    "bath_magistrates_court.jpg",
    "oxford_social_security_child_support_tribunal.jpg",
    "abergavenny_magistrates_court.jpg",
    "hereford_county_court_and_family_court.jpg",
    "st_helens_county_court.jpg",
    "chester_civil_justice_centre.jpg",
    "leeds_district_probate_registry.jpg",
    "leeds_employment_tribunal.jpg",
    "milton_keynes_magistrates_court_and_family_court.jpg",
    "reading_employment_tribunal.jpg",
    "lewes_combined_court_centre.jpg",
    "chichester_combined_court_centre.jpg",
    "merthyr_tydfil_combined_court_centre.jpg",
    "weston_super_mare_county_court.jpg",
    "gateshead_magistrates_court.jpg",
    "court_of_appeal_criminal_division.jpg",
    "mayor_s_and_city_of_london_court.jpg",
    "reading_crown_court.jpg",
    "bradford_tribunal_hearing_centre.jpg",
    "nottingham-social-security-and-child-support-tribunal.jpg",
    "winchester_combined_court_centre.jpg",
    "eastbourne_county_court.jpg",
    "doncaster_county_court.jpg",
    "carmarthen_crown_court.jpg",
    "reigate_county_court.jpg",
    "carmarthen_magistrates_court.jpg",
    "durham_crown_court.jpg",
    "truro_magistrates_court.jpg",
    "lancaster_magistrates_court.jpg",
    "leeds_social_security_and_child_support_tribunal.jpg",
    "thanet_county_court.jpg",
    "hastings_county_court.jpg",
    "weymouth_combined_court.png",
    "high_wycombe_magistrates_court_and_family_court.jpg",
    "highbury_corner_magistrates_court.jpg",
    "sheffield_magistrates_court.jpg",
    "newcastle_moot_hall.jpg",
    "brighton_county_court.jpg",
    "harrogate_magistrates_court.jpg",
    "liverpool_knowsley_magistrates_court.jpg",
    "carlisle_magistrates_court.jpg",
    "sunderland_magistrates_court.jpg",
    "port_talbot_magistrates_court.jpg",
    "kendal_magistrates_court.jpg",
    "burnley_combined_court_centre.jpg",
    "dorchester_crown_court.jpg",
    "neath_magistrates_court.jpg",
    "east_berkshire_magistrates_court_bracknell.jpg",
    "peterborough_probate_sub_registry.jpg",
    "leicester_county_court_and_family_court.jpg",
    "port_talbot_regional_divorce_centre.jpg",
    "wrexham_regional_divorce_centre.jpg",
    "watford_employment_tribunal.bmp",
    "glasgow_tribunal_centre.jpg",
    "north_staffordshire_justice_centre.jpg",
    "manchester_employment_tribunal.jpeg",
    "dudley_magistrates_court.jpg",
    "romford_county_court.jpg",
    "kidderminster_magistrates_court.jpg",
    "bradford_regional_divorce_centre.bmp",
    "portsmouth_combined_court_centre.jpg",
    "llandrindod_wells_magistrates_court.jpg",
    "mansfield_magistrates_and_county_courts.jpg",
    "weymouth_and_dorchester_combined_court_centre.png",
    "high_wycombe_county_court.jpg",
    "worthing_magistrates_court.jpg",
    "norwich_combined_court_centre.jpg",
    "taunton_county_court.jpg",
    "central_london_county_court.jpg",
    "norwich_magistrates_court.jpg",
    "southend-county-court-and-family-court.jpg",
    "lincoln_crown_court.jpg",
    "bristol_magistrates_court.jpg",
    "cambridge_county_court.jpg",
    "south_somerset_mendip_magistrates_court.jpg",
    "croydon_crown_court.jpg",
    "chelmsford_county_and_family_proceedings_court.jpg",
    "maintenance_enforcement_centre_england.jpg",
    "middlesbrough_county_court_at_teesside_combined_court.jpg",
    "court_of_protection.jpg",
    "uxbridge_county_court_and_family_court.bmp",
    "reading_county_court.jpg",
    "clerkenwell_and_shoreditch_county_court.jpg",
    "hendon_magistrates_court.jpg",
    "bedford_county_court.jpg",
    "edmonton_county_court.jpg",
    "colchester_county_court.jpg",
    "ipswich_county_court.jpg",
    "southwark_crown_court.jpg",
    "gloucester_and_cheltenham_county_court.jpg",
    "royal_courts_of_justice.jpg",
    "stoke_on_trent_combined_court.jpg",
    "manchester_county_court.jpg",
    "ipswich_district_probate_registry.jpg",
    "stafford_combined_court_centre.jpg",
    "cwmbran_magistrates_court.jpg",
    "maidstone_combined_court_centre.jpg",
    "portsmouth_magistrates_court.jpg",
    "nuneaton_magistrates_court.jpg",
    "birmingham_district_probate_registry.jpg",
    "chelmsford_magistrates_court.jpg",
    "prestatyn_magistrates_court.jpg",
    "bromley_county_court.jpg",
    "bury_st_edmunds_divorce_centre.jpg",
    "liverpool_civil_and_family_court.jpg",
    "stockport_magistrates_and_county_courts.jpg",
    "cardiff_crown_court.jpg",
    "coventry_combined_court_centre.jpg",
    "peterlee_magistrates_court.jpg",
    "exeter_probate_sub_registry.jpg",
    "hull-tribunal-hearing-centre.jpg",
    "willesden_county_court.jpg",
    "tameside_magistrates_court.jpg",
    "dudley_county_court_and_family_court.jpg",
    "chorley_magistrates_court.jpg",
    "manchester_crown_court_minshull_st.jpg",
    "crewe_county_court.jpg",
    "blackwood_civil_and_family_court.jpg",
    "kingston_upon_thames_county_court.jpg",
    "north_somerset_magistrates_court.jpg",
    "bexley_magistrates_court.jpg",
    "ealing_magistrates_court.jpg",
    "money_claim_online_mcol.jpg",
    "torquay_and_newton_abbot_county_court.jpg",
    "thames_magistrates_court.jpg",
    "bristol_civil_justice_centre.jpg",
    "derby_combined_court_centre.jpg",
    "barrow_in_furness_magistrates_court.jpg",
    "taunton_deane_magistrates_court.jpg",
    "nottingham_county_court.jpg",
    "carmarthen_county_court.jpg",
    "blackpool_county_court.jpg",
    "medway_county_court.jpg",
    "leyland_magistrates_court_and_family_court.jpg",
    "coventry_magistrates_court.jpg",
    "mold_county_court.jpg",
    "newport_gwent_civil_and_family_court.jpg",
    "blackpool_magistrates_court.jpg",
    "wandsworth_county_court.jpg",
    "northampton-crown-county-and-family-court.jpg",
    "stratford_magistrates_court.jpg",
    "southampton_combined_court_centre.jpg",
    "newcastle_district_probate_registry.jpg",
    "bradford_combined_court_centre.jpg",
    "boston_county_court.jpg",
    "camberwell_green_magistrates_court.jpg",
    "boston_magistrates_court.jpg",
    "preston_crown_court_sessions_house.jpg",
    "willesden_magistrates_court.jpg",
    "telford-county-court-and-family-court.jpg",
    "wimbledon_magistrates_court.jpg",
    "cardiff_civil_justice_centre.jpg",
    "newport_asylum_and_immigration_tribunal.bmp",
    "lavender_hill_magistrates_court_formerly_south_western_magistrates_court.jpg",
    "uxbridge_magistrates_court.jpg",
    "glasgow_tribunal_hearing_centre.jpg",
    "croydon_magistrates_court.jpg",
    "croydon_county_court.jpg",
    "darlington_county_court.jpg",
    "blackfriars_crown_court.jpg",
    "inner_london_crown_court.jpg",
    "swansea_civil_justice_centre.jpg",
    "swansea_crown_court.jpg",
    "swansea_magistrates_court.jpg",
    "birmingham_civil_justice_centre_and_family_courts.jpg",
    "tax-chamber-first-tier-tribunal.jpg",
    "marks-test-court1.jpg",
    "birmingham-crown-court.jpg",
    "birmingham-immigration-and-asylum-chamber-first-tier-tribunal.jpg",
    "birmingham_magistrates_court.jpg",
    "birmingham-youth-court.jpg",
    "admiralty_and_commercial_court.jpg",
    "amersham_law_courts.jpg",
    "avon_and_somerset_central_accounts_department.jpg",
    "ayr_social_security_and_child_support_tribunal.jpg",
    "bankruptcy_court_central_london.jpg",
    "bankruptcy_court_high_court.jpg",
    "barkingside_magistrates_court.jpg",
    "basildon_magistrates_court.jpg",
    "cardiff_and_the_vale_magistrates_court.jpg",
    "aldershot_magistrates_court.jpg",
    "aberystwyth_justice_centre.jpg",
  ]
}

resource "azurerm_resource_group" "rg" {
  name     = "${var.product}-${var.env}"
  location = var.location

  tags = var.common_tags
}

module "key-vault" {
  source              = "git@github.com:hmcts/cnp-module-key-vault?ref=azurermv2"
  product             = var.product
  env                 = var.env
  tenant_id           = var.tenant_id
  object_id           = var.jenkins_AAD_objectId
  resource_group_name = azurerm_resource_group.rg.name

  # dcd_platformengineering group object ID
  product_group_object_id    = "c36eaede-a0ae-4967-8fed-0a02960b1370"
  common_tags                = var.common_tags
  create_managed_identity    = true
}

resource "azurerm_key_vault_secret" "AZURE_APPINSIGHTS_KEY" {
  name         = "AppInsightsInstrumentationKey"
  value        = azurerm_application_insights.appinsights.instrumentation_key
  key_vault_id = module.key-vault.key_vault_id
}

resource "azurerm_application_insights" "appinsights" {
  name                = "${var.product}-appinsights-${var.env}"
  location            = var.appinsights_location
  resource_group_name = azurerm_resource_group.rg.name
  application_type    = "web"

  tags = var.common_tags

  lifecycle {
    ignore_changes = [
      # Ignore changes to appinsights as otherwise upgrading to the Azure provider 2.x
      # destroys and re-creates this appinsights instance
      application_type,
    ]
  }
}

resource "azurerm_storage_account" "storage_account" {
  name                = replace("${var.product}${var.env}", "-", "")
  resource_group_name = azurerm_resource_group.rg.name

  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "BlobStorage"
  allow_blob_public_access = true

  tags = var.common_tags
}

resource "azurerm_storage_container" "images" {
  name                  = "images"
  storage_account_name  = azurerm_storage_account.storage_account.name
  container_access_type = "container"
}

resource "azurerm_storage_blob" "images" {
  name                   = local.images[count.index]
  storage_account_name   = azurerm_storage_account.storage_account.name
  storage_container_name = azurerm_storage_container.images.name
  type                   = "Block"
  source_uri             = "https://8d96a24990d0prodcf.blob.core.windows.net/media/images/${local.images[count.index]}"
  count                  = length(local.images)
}

resource "azurerm_key_vault_secret" "storage_account_name" {
  name      = "storage-account-name"
  value     = azurerm_storage_account.storage_account.name
  key_vault_id = module.key-vault.key_vault_id
}

resource "azurerm_key_vault_secret" "storage_account_primary_key" {
  name      = "storage-account-primary-key"
  value     = azurerm_storage_account.storage_account.primary_access_key
  key_vault_id = module.key-vault.key_vault_id
}

resource "azurerm_key_vault_secret" "storage_account_connection_string" {
  name      = "storage-account-connection-string"
  value     = azurerm_storage_account.storage_account.primary_connection_string
  key_vault_id = module.key-vault.key_vault_id
}

output "storage_account_name" {
  value = azurerm_storage_account.storage_account.name
}

output "storage_account_primary_key" {
  sensitive = true
  value     = azurerm_storage_account.storage_account.primary_access_key
}
